print("jeevitha Python file")
print("Jila")
print("Suraj Karthic")
print("Rohindh Kishore K M")
print("Jila")
print("Sanskriti")
print("Suraj Karthic Python file")
print("Aditya Trivedi")
print("Subash")
print("Ayush")
print("Stephen Adithya")
print("sandeepkumar")
print("Sindhu")