name: hello world

on: workflow_dispatch
jobs:  
  hello_world:
    runs-on: ubuntu-latest
    steps:
      -  name: hello
         run: echo "hello moto"
      -  name: goodbye
         run: echo "good bye"

         
      -  name: Lint Code Base
         uses: super-linter/super-linter@v5
         env:
           VALIDATE_ALL_CODEBASE: false
           DEFAULT_BRANCH: main
            #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
