name: hello world

on: workflow_dispatch
jobs:  
  hello_world:
    runs-on: ubuntu-latest
    steps:
      -  name: hello
         run: echo "hello moto"
      -  name: goodbye
         run: echo "good bye"
